#!/bin/bash

# ═════════════════════════════════════════════════════════════
# WhatsApp API - WEBHOOK SETUP QUICK START GUIDE
# ═════════════════════════════════════════════════════════════

echo "🚀 WhatsApp API Server Setup Guide"
echo "══════════════════════════════════════════════════════════=="
echo ""
echo "✅ Server Status: RUNNING"
echo "📍 URL: http://localhost:3002"
echo "🔌 Port: 3002"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "📋 STEP-BY-STEP WEBHOOK SETUP GUIDE:"
echo ""
echo "STEP 1️⃣  - ACCESS THE WEBSITE"
echo "────────────────────────────────"
echo "  👉 Open browser and go to: http://localhost:3002"
echo "  👉 You will be redirected to login page"
echo ""
echo "STEP 2️⃣  - REGISTER/LOGIN"
echo "────────────────────────────────"
echo "  👉 Click 'Register' button"
echo "  👉 Fill in details:"
echo "     • Name: Your Name"
echo "     • Username: your_username (lowercase, no spaces)"
echo "     • Email: your@email.com"
echo "     • Password: strong_password"
echo "  👉 Click 'Register'"
echo ""
echo "STEP 3️⃣  - LOGIN"
echo "────────────────────────────────"
echo "  👉 Enter username/email and password"
echo "  👉 Click 'Login'"
echo ""
echo "STEP 4️⃣  - CREATE WHATSAPP SESSION"
echo "────────────────────────────────"
echo "  👉 Go to 'Sessions' page from menu"
echo "  👉 Click 'Create Session' button"
echo "  👉 Enter session name (e.g., 'My Session')"
echo "  👉 Click 'Create'"
echo "  👉 Scan QR code with WhatsApp mobile app"
echo "  👉 Wait for 'Connected' status"
echo ""
echo "STEP 5️⃣  - CONFIGURE WEBHOOK"
echo "────────────────────────────────"
echo "  👉 In Sessions page, find your session"
echo "  👉 Click the '🔗 Webhook' button (link icon)"
echo "  👉 In popup modal:"
echo "     • 'Current Webhook URL' - shows existing webhook"
echo "     • 'New Webhook URL' - enter your webhook URL"
echo ""
echo "      Example webhook URLs (for testing):"
echo "      ─────────────────────────────────────"
echo "      📌 Local Testing (ngrok):"
echo "        https://abc123.ngrok.io/webhook"
echo ""
echo "      📌 Online Testing: https://webhook.site"
echo "        1. Go to https://webhook.site"
echo "        2. Copy your unique URL"
echo "        3. Paste it here as webhook URL"
echo ""
echo "      📌 Your Server:"
echo "        https://your-domain.com/api/webhook"
echo ""
echo "  👉 Click 'Save' button"
echo "  👉 Success message: 'Webhook Updated'"
echo ""
echo "STEP 6️⃣  - WEBHOOK IS NOW ACTIVE! 🎉"
echo "────────────────────────────────"
echo "  ✅ Server will now send events to your webhook URL when:"
echo "     • WhatsApp message is received"
echo "     • Message is sent via API"
echo "     • Session connects/disconnects"
echo "     • Session reconnects"
echo "     • User logs out"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "🧪 TESTING WEBHOOK SETUP:"
echo "────────────────────────────────"
echo ""
echo "Option 1: Using webhook.site (EASIEST FOR TESTING)"
echo "─────────────────────────────────────────────────"
echo "  1. Open: https://webhook.site"
echo "  2. Copy the unique URL displayed"
echo "  3. Paste it as webhook URL in the modal"
echo "  4. Send a WhatsApp message"
echo "  5. Check webhook.site - you'll see the event data!"
echo ""
echo "Option 2: Using ngrok"
echo "─────────────────────────────────────────────────"
echo "  1. Download ngrok: https://ngrok.com/download"
echo "  2. Run ngrok on your local server:"
echo "     ngrok http 3000  (if your webhook server is on 3000)"
echo "  3. Copy ngrok URL (e.g., https://abc123.ngrok.io)"
echo "  4. Create webhook endpoint on your server:"
echo "     app.post('/webhook', (req, res) => {"
echo "       console.log('Webhook received:', req.body);"
echo "       res.json({ success: true });"
echo "     });"
echo "  5. Set webhook URL: https://abc123.ngrok.io/webhook"
echo ""
echo "Option 3: Your Own Server"
echo "─────────────────────────────────────────────────"
echo "  1. Set up webhook handler on your server"
echo "  2. Make sure it's accessible from internet (HTTPS)"
echo "  3. Set webhook URL in the modal"
echo "  4. Events will be sent in real-time"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "📊 WEBHOOK EVENT EXAMPLES:"
echo "────────────────────────────────"
echo ""
echo "When message is RECEIVED:"
echo "──────────────────────────"
echo "  {\"
echo "    \"event\": \"message.received\","
echo "    \"timestamp\": \"2024-03-26T12:34:56.789Z\","
echo "    \"sessionId\": \"session_id\","
echo "    \"data\": {"
echo "      \"from\": \"1234567890\","
echo "      \"message\": \"Hello!\","
echo "      \"type\": \"text\""
echo "    }"
echo "  }"
echo ""
echo "When message is SENT (via API):"
echo "──────────────────────────────"
echo "  {\"
echo "    \"event\": \"message.sent\","
echo "    \"timestamp\": \"2024-03-26T12:34:56.789Z\","
echo "    \"sessionId\": \"session_id\","
echo "    \"data\": {"
echo "      \"to\": \"1234567890\","
echo "      \"messageId\": \"message_12345\","
echo "      \"status\": \"sent\""
echo "    }"
echo "  }"
echo ""
echo "When SESSION CONNECTS:"
echo "──────────────────────────────"
echo "  {\"
echo "    \"event\": \"session.connected\","
echo "    \"timestamp\": \"2024-03-26T12:34:56.789Z\","
echo "    \"sessionId\": \"session_id\","
echo "    \"data\": {"
echo "      \"phoneNumber\": \"1234567890@c.us\","
echo "      \"name\": \"User Name\","
echo "      \"status\": \"connected\""
echo "    }"
echo "  }"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "❓ TROUBLESHOOTING:"
echo "────────────────────────────────"
echo ""
echo "❌ Webhook not firing?"
echo "  ✅ Check webhook URL is HTTPS"
echo "  ✅ Check session status is 'CONNECTED'"
echo "  ✅ Send a message to the session"
echo "  ✅ Check server console for errors"
echo ""
echo "❌ Connection timeout?"
echo "  ✅ Make sure your webhook endpoint returns in <10s"
echo "  ✅ Use async processing for long operations"
echo "  ✅ Check firewall allows outbound requests"
echo ""
echo "❌ Invalid webhook URL error?"
echo "  ✅ Must start with https://"
echo "  ✅ Must be valid URL format"
echo "  ✅ Try using webhook.site first to test"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "✨ ALL SET! Your webhook is ready to use! 🎉"
echo ""
